[json_file]
extensions = ["json", "json5", "jsonc", "jsonl", "jsond"]

[python_file]
extensions = ["ipynb", "py", "pyde", "pyi", "pyp", "pyt", "pyw"]
filenames = ["Pipfile"]

[sublime_file]
extensions = ["sublime-build", "sublime-keymap", "sublime-macro", "sublime-project", "sublime-settings", "sublime-snippet", "sublime-syntax", "sublime-workspace"]

[toml_file]
extensions = ["toml"]

[tsconfig_file]
filenames = ["tsconfig.json"]

[xml_file]
extensions = ["admx", "aseprite-data", "aseprite-keys", "filters", "ivy", "jelly", "mxml", "nuspec", "resx", "targets", "tld", "wsdl", "xib", "xlf", "xliff", "xmi", "xml", "xsd", "xsl", "xslt"]

[yaml_file]
extensions = ["rviz", "yaml", "yml"]

[javascript_file]
extensions = ["cjs", "es6", "jake", "js", "jsm", "jss", "mjs", "pac"]

[julia_file]
extensions = ["jl"]