shell_file = "\U0001fa8e\uf800"
cargo_file = "\U0001fa8e\uf801"
vs_file = "\U0001fa8e\uf802"
docker_folder_xmas = "\U0001fa8e\uf803"
src_folder_closed = "\U0001fa8e\uf804"
blocks_file = "\U0001fa8e\uf805"
mcfunction_file = "\U0001fa8e\uf806"
executable_file = "\U0001fa8e\uf807"
trading_file = "\U0001fa8e\uf808"
gradle_file = "\U0001fa8e\uf809"
features_file = "\U0001fa8e\uf80a"
zig_file = "\U0001fa8e\uf80b"
xml_file = "\U0001fa8e\uf80c"
instrument_folder = "\U0001fa8e\uf80d"
namespace_folder = "\U0001fa8e\uf80e"
frog_variant_folder_xmas = "\U0001fa8e\uf80f"
test_instance_file = "\U0001fa8e\uf810"
objective_c_file = "\U0001fa8e\uf811"
enchantment_folder = "\U0001fa8e\uf812"
c_header_file = "\U0001fa8e\uf813"
gradle_folder_xmas = "\U0001fa8e\uf814"
items_folder_xmas = "\U0001fa8e\uf815"
git_folder = "\U0001fa8e\uf816"
tsconfig_file = "\U0001fa8e\uf817"
cplusplus_header_file = "\U0001fa8e\uf818"
overlay_folder_closed = "\U0001fa8e\uf819"
holy_c_file = "\U0001fa8e\uf81a"
javascript_folder = "\U0001fa8e\uf81b"
block_culling_folder = "\U0001fa8e\uf81c"
terraform_file = "\U0001fa8e\uf81d"
trial_spawner_folder = "\U0001fa8e\uf81e"
advancement_file = "\U0001fa8e\uf81f"
mcfunction_load_file_crowned = "\U0001fa8e\uf820"
godot_file = "\U0001fa8e\uf821"
valve_file = "\U0001fa8e\uf822"
"test.js_file" = "\U0001fa8e\uf823"
pascal_file = "\U0001fa8e\uf824"
models_file = "\U0001fa8e\uf825"
wolf_variant_folder = "\U0001fa8e\uf826"
attachables_file = "\U0001fa8e\uf827"
image_folder_xmas = "\U0001fa8e\uf828"
materials_folder_xmas = "\U0001fa8e\uf829"
spyglass_folder_xmas = "\U0001fa8e\uf82a"
spawn_rules_folder_xmas = "\U0001fa8e\uf82b"
cat_variant_folder = "\U0001fa8e\uf82c"
julia_folder = "\U0001fa8e\uf82d"
recipe_folder = "\U0001fa8e\uf82e"
generic_folder_closed = "\U0001fa8e\uf82f"
banner_pattern_folder = "\U0001fa8e\uf830"
csharp_file = "\U0001fa8e\uf831"
todo_folder_xmas = "\U0001fa8e\uf832"
config_folder_xmas = "\U0001fa8e\uf833"
vim_folder = "\U0001fa8e\uf834"
godotignore_file = "\U0001fa8e\uf835"
jar_folder_xmas = "\U0001fa8e\uf836"
ajmeta_file = "\U0001fa8e\uf837"
test_environment_file = "\U0001fa8e\uf838"
cat_variant_file = "\U0001fa8e\uf839"
"requirements.txt_file" = "\U0001fa8e\uf83a"
dart_file = "\U0001fa8e\uf83b"
contributing_file = "\U0001fa8e\uf83c"
atlases_folder_xmas = "\U0001fa8e\uf83d"
forge_file = "\U0001fa8e\uf83e"
vscodeignore_file = "\U0001fa8e\uf83f"
assembly_file = "\U0001fa8e\uf840"
loot_table_file = "\U0001fa8e\uf841"
prettierignore_file = "\U0001fa8e\uf842"
clojure_file = "\U0001fa8e\uf843"
ejs_file = "\U0001fa8e\uf844"
dart_folder = "\U0001fa8e\uf845"
android_file = "\U0001fa8e\uf846"
namespace_folder_closed_xmas = "\U0001fa8e\uf847"
font_folder = "\U0001fa8e\uf848"
license_file = "\U0001fa8e\uf849"
archive_folder_xmas = "\U0001fa8e\uf84a"
item_modifier_folder = "\U0001fa8e\uf84b"
jukebox_song_folder = "\U0001fa8e\uf84c"
pig_variant_folder_xmas = "\U0001fa8e\uf84d"
atlases_folder = "\U0001fa8e\uf84e"
hjmc_file = "\U0001fa8e\uf84f"
docker_folder = "\U0001fa8e\uf850"
shell_folder_xmas = "\U0001fa8e\uf851"
godot_folder = "\U0001fa8e\uf852"
spyglass_folder = "\U0001fa8e\uf853"
haskell_file = "\U0001fa8e\uf854"
ruby_file = "\U0001fa8e\uf855"
data_folder = "\U0001fa8e\uf856"
shaders_file = "\U0001fa8e\uf857"
aseprite_file = "\U0001fa8e\uf858"
src_folder = "\U0001fa8e\uf859"
"tick.json_file" = "\U0001fa8e\uf85a"
ui_folder_xmas = "\U0001fa8e\uf85b"
binary_file = "\U0001fa8e\uf85c"
features_folder = "\U0001fa8e\uf85d"
zombie_nautilus_variant_file = "\U0001fa8e\uf85e"
test_instance_folder = "\U0001fa8e\uf85f"
terraform_folder_xmas = "\U0001fa8e\uf860"
banner_pattern_file = "\U0001fa8e\uf861"
test_environment_folder = "\U0001fa8e\uf862"
loom_file = "\U0001fa8e\uf863"
cargo_folder = "\U0001fa8e\uf864"
vim_file = "\U0001fa8e\uf865"
video_folder_xmas = "\U0001fa8e\uf866"
fogs_folder = "\U0001fa8e\uf867"
jukebox_song_folder_xmas = "\U0001fa8e\uf868"
executable_folder_xmas = "\U0001fa8e\uf869"
html_file = "\U0001fa8e\uf86a"
jmc_file = "\U0001fa8e\uf86b"
tags_folder_xmas = "\U0001fa8e\uf86c"
trim_material_folder_xmas = "\U0001fa8e\uf86d"
namespace_folder_closed = "\U0001fa8e\uf86e"
nim_file = "\U0001fa8e\uf86f"
pixi_file = "\U0001fa8e\uf870"
vscode_folder = "\U0001fa8e\uf871"
flare_file = "\U0001fa8e\uf872"
tags_folder = "\U0001fa8e\uf873"
audio_file = "\U0001fa8e\uf874"
css_folder_xmas = "\U0001fa8e\uf875"
beet_file = "\U0001fa8e\uf876"
c_file = "\U0001fa8e\uf877"
blocks_folder_xmas = "\U0001fa8e\uf878"
loot_table_folder_xmas = "\U0001fa8e\uf879"
editorconfig_file = "\U0001fa8e\uf87a"
"splashes.json_file" = "\U0001fa8e\uf87b"
cat_variant_folder_xmas = "\U0001fa8e\uf87c"
godot_project_file = "\U0001fa8e\uf87d"
items_folder = "\U0001fa8e\uf87e"
database_folder = "\U0001fa8e\uf87f"
dimension_file = "\U0001fa8e\uf880"
chat_type_folder = "\U0001fa8e\uf881"
sublime_file = "\U0001fa8e\uf882"
blocks_folder = "\U0001fa8e\uf883"
sponge_mixins_file = "\U0001fa8e\uf884"
npm_file = "\U0001fa8e\uf885"
timeline_folder = "\U0001fa8e\uf886"
typescript_file = "\U0001fa8e\uf887"
vs_folder_xmas = "\U0001fa8e\uf888"
dimension_folder = "\U0001fa8e\uf889"
gamemaker_file = "\U0001fa8e\uf88a"
sulfur_cube_archetype_file = "\U0001fa8e\uf88b"
julia_folder_xmas = "\U0001fa8e\uf88c"
maven_folder = "\U0001fa8e\uf88d"
javascript_file = "\U0001fa8e\uf88e"
chat_type_folder_xmas = "\U0001fa8e\uf88f"
dlang_file = "\U0001fa8e\uf890"
chat_type_file = "\U0001fa8e\uf891"
enchantment_file = "\U0001fa8e\uf892"
chicken_variant_folder_xmas = "\U0001fa8e\uf893"
python_folder = "\U0001fa8e\uf894"
python_compiled_file = "\U0001fa8e\uf895"
vscode_folder_xmas = "\U0001fa8e\uf896"
prisma_file = "\U0001fa8e\uf897"
rlang_file = "\U0001fa8e\uf898"
ui_file = "\U0001fa8e\uf899"
config_file = "\U0001fa8e\uf89a"
features_folder_xmas = "\U0001fa8e\uf89b"
elm_folder_xmas = "\U0001fa8e\uf89c"
assets_folder = "\U0001fa8e\uf89d"
toml_file = "\U0001fa8e\uf89e"
jetbrains_folder_xmas = "\U0001fa8e\uf89f"
spawn_rules_folder = "\U0001fa8e\uf8a0"
dialog_file = "\U0001fa8e\uf8a1"
worldgen_folder_xmas = "\U0001fa8e\uf8a2"
block_culling_folder_xmas = "\U0001fa8e\uf8a3"
fortran_file = "\U0001fa8e\uf8a4"
fogs_file = "\U0001fa8e\uf8a5"
playdate_file = "\U0001fa8e\uf8a6"
generic_folder = "\U0001fa8e\uf8a7"
spwn_file = "\U0001fa8e\uf8a8"
"pack.mcmeta_file" = "\U0001fa8e\uf8a9"
jsconfig_file = "\U0001fa8e\uf8aa"
markdown_file = "\U0001fa8e\uf8ab"
maven_folder_xmas = "\U0001fa8e\uf8ac"
linux_folder_xmas = "\U0001fa8e\uf8ad"
attachables_folder_xmas = "\U0001fa8e\uf8ae"
crystal_file = "\U0001fa8e\uf8af"
python_file = "\U0001fa8e\uf8b0"
ui_folder = "\U0001fa8e\uf8b1"
pig_variant_file = "\U0001fa8e\uf8b2"
"level.dat_file" = "\U0001fa8e\uf8b3"
shaders_folder = "\U0001fa8e\uf8b4"
items_file = "\U0001fa8e\uf8b5"
cplusplus_file = "\U0001fa8e\uf8b6"
haxe_file = "\U0001fa8e\uf8b7"
aseprite_extension_file = "\U0001fa8e\uf8b8"
equipment_folder_xmas = "\U0001fa8e\uf8b9"
typst_file = "\U0001fa8e\uf8ba"
item_modifier_folder_xmas = "\U0001fa8e\uf8bb"
lua_file = "\U0001fa8e\uf8bc"
gradle_folder = "\U0001fa8e\uf8bd"
php_file = "\U0001fa8e\uf8be"
damage_type_folder_xmas = "\U0001fa8e\uf8bf"
cargo_folder_xmas = "\U0001fa8e\uf8c0"
namespace_folder_xmas = "\U0001fa8e\uf8c1"
executable_folder = "\U0001fa8e\uf8c2"
spawn_rules_file = "\U0001fa8e\uf8c3"
image_file = "\U0001fa8e\uf8c4"
yaml_file = "\U0001fa8e\uf8c5"
trim_material_file = "\U0001fa8e\uf8c6"
atlases_file = "\U0001fa8e\uf8c7"
erlang_file = "\U0001fa8e\uf8c8"
rust_file = "\U0001fa8e\uf8c9"
trim_pattern_folder = "\U0001fa8e\uf8ca"
particles_file = "\U0001fa8e\uf8cb"
dialog_folder = "\U0001fa8e\uf8cc"
swift_file = "\U0001fa8e\uf8cd"
github_folder_xmas = "\U0001fa8e\uf8ce"
frog_variant_folder = "\U0001fa8e\uf8cf"
scala_folder_xmas = "\U0001fa8e\uf8d0"
enchantment_folder_xmas = "\U0001fa8e\uf8d1"
elm_file = "\U0001fa8e\uf8d2"
dimension_folder_xmas = "\U0001fa8e\uf8d3"
linux_folder = "\U0001fa8e\uf8d4"
jar_folder = "\U0001fa8e\uf8d5"
web_assembly_file = "\U0001fa8e\uf8d6"
jetbrains_file = "\U0001fa8e\uf8d7"
kotlin_file = "\U0001fa8e\uf8d8"
lang_folder_xmas = "\U0001fa8e\uf8d9"
blockstates_file = "\U0001fa8e\uf8da"
function_folder_xmas = "\U0001fa8e\uf8db"
mongodb_file = "\U0001fa8e\uf8dc"
zig_folder_xmas = "\U0001fa8e\uf8dd"
dimension_type_folder_xmas = "\U0001fa8e\uf8de"
cow_variant_folder_xmas = "\U0001fa8e\uf8df"
ocaml_file = "\U0001fa8e\uf8e0"
assets_folder_closed = "\U0001fa8e\uf8e1"
zombie_nautilus_variant_folder = "\U0001fa8e\uf8e2"
entities_folder_xmas = "\U0001fa8e\uf8e3"
sulfur_cube_archetype_folder = "\U0001fa8e\uf8e4"
banner_pattern_folder_xmas = "\U0001fa8e\uf8e5"
log_folder = "\U0001fa8e\uf8e6"
font_file = "\U0001fa8e\uf8e7"
lang_file = "\U0001fa8e\uf8e8"
lisp_file = "\U0001fa8e\uf8e9"
generic_folder_closed_xmas = "\U0001fa8e\uf8ea"
generic_file = "\U0001fa8e\uf8eb"
mcfunction_file_crowned = "\U0001fa8e\uf8ec"
todo_folder = "\U0001fa8e\uf8ed"
zig_folder = "\U0001fa8e\uf8ee"
zombie_nautilus_variant_folder_xmas = "\U0001fa8e\uf8ef"
overlay_folder = "\U0001fa8e\uf8f0"
pdf_file = "\U0001fa8e\uf8f1"
entities_file = "\U0001fa8e\uf8f2"
worldgen_folder = "\U0001fa8e\uf8f3"
equipment_file = "\U0001fa8e\uf8f4"
materials_folder = "\U0001fa8e\uf8f5"
timeline_file = "\U0001fa8e\uf8f6"
nbt_file = "\U0001fa8e\uf8f7"
gitignore_file = "\U0001fa8e\uf8f8"
dart_folder_xmas = "\U0001fa8e\uf8f9"
mojo_file = "\U0001fa8e\uf8fa"
datapacks_folder_xmas = "\U0001fa8e\uf8fb"
fennel_file = "\U0001fa8e\uf8fc"
predicate_folder_xmas = "\U0001fa8e\uf8fd"
javascript_folder_xmas = "\U0001fa8e\uf8fe"
svelte_file = "\U0001fa8e\uf8ff"
datapacks_folder = "\U0001fa8e豈"
graphql_file = "\U0001fa8e更"
gleam_file = "\U0001fa8e車"
fragment_shader_file = "\U0001fa8e賈"
bolt_file = "\U0001fa8e滑"
structure_folder = "\U0001fa8e串"
excel_file = "\U0001fa8e句"
particles_folder = "\U0001fa8e龜"
text_folder = "\U0001fa8e龜"
neovim_file = "\U0001fa8e契"
vscode_file = "\U0001fa8e金"
archive_folder = "\U0001fa8e喇"
test_instance_folder_xmas = "\U0001fa8e奈"
test_environment_folder_xmas = "\U0001fa8e懶"
audio_folder_xmas = "\U0001fa8e癩"
github_folder = "\U0001fa8e羅"
font_folder_xmas = "\U0001fa8e蘿"
autohotkey_file = "\U0001fa8e螺"
chicken_variant_file = "\U0001fa8e裸"
particles_folder_xmas = "\U0001fa8e邏"
godot_folder_xmas = "\U0001fa8e樂"
trim_pattern_file = "\U0001fa8e洛"
go_file = "\U0001fa8e烙"
json_file = "\U0001fa8e珞"
lock_file = "\U0001fa8e落"
materials_file = "\U0001fa8e酪"
worldgen_file = "\U0001fa8e駱"
rss_file = "\U0001fa8e亂"
scala_folder = "\U0001fa8e卵"
vim_folder_xmas = "\U0001fa8e欄"
render_controllers_folder_xmas = "\U0001fa8e爛"
entities_folder = "\U0001fa8e蘭"
git_folder_xmas = "\U0001fa8e鸞"
video_folder = "\U0001fa8e嵐"
prettier_file = "\U0001fa8e濫"
loot_table_folder = "\U0001fa8e藍"
cow_variant_file = "\U0001fa8e襤"
video_file = "\U0001fa8e拉"
npm_folder = "\U0001fa8e臘"
advancement_folder = "\U0001fa8e蠟"
trial_spawner_folder_xmas = "\U0001fa8e廊"
"biomes_client.json_file" = "\U0001fa8e朗"
latex_file = "\U0001fa8e浪"
trading_folder_xmas = "\U0001fa8e狼"
database_file = "\U0001fa8e郎"
mcfunction_tick_file_crowned = "\U0001fa8e來"
jetbrains_folder = "\U0001fa8e冷"
blazor_file = "\U0001fa8e勞"
audio_folder = "\U0001fa8e擄"
timeline_folder_xmas = "\U0001fa8e櫓"
wolf_variant_folder_xmas = "\U0001fa8e爐"
readme_file = "\U0001fa8e盧"
elm_folder = "\U0001fa8e老"
fabric_file = "\U0001fa8e蘆"
predicate_file = "\U0001fa8e虜"
"load.json_file" = "\U0001fa8e路"
fox_file = "\U0001fa8e露"
maven_file = "\U0001fa8e魯"
render_controllers_file = "\U0001fa8e鷺"
copyright_file = "\U0001fa8e碌"
blockstates_folder = "\U0001fa8e祿"
vertex_shader_file = "\U0001fa8e綠"
config_folder = "\U0001fa8e菉"
perl_file = "\U0001fa8e錄"
document_file = "\U0001fa8e鹿"
shell_folder = "\U0001fa8e論"
pig_variant_folder = "\U0001fa8e壟"
structure_file = "\U0001fa8e弄"
npmignore_file = "\U0001fa8e籠"
render_controllers_folder = "\U0001fa8e聾"
fsharp_file = "\U0001fa8e牢"
block_culling_file = "\U0001fa8e磊"
trading_folder = "\U0001fa8e賂"
purpur_file = "\U0001fa8e雷"
"test.ts_file" = "\U0001fa8e壘"
moonscript_file = "\U0001fa8e屢"
cow_variant_folder = "\U0001fa8e樓"
brainfuck_file = "\U0001fa8e淚"
jar_file = "\U0001fa8e漏"
quilt_file = "\U0001fa8e累"
mcfunction_tick_file = "\U0001fa8e縷"
waypoint_style_folder = "\U0001fa8e陋"
models_folder = "\U0001fa8e勒"
mcfunction_load_file = "\U0001fa8e肋"
odin_file = "\U0001fa8e凜"
log_folder_xmas = "\U0001fa8e凌"
fogs_folder_xmas = "\U0001fa8e稜"
jukebox_song_file = "\U0001fa8e綾"
python_folder_xmas = "\U0001fa8e菱"
neovim_folder = "\U0001fa8e陵"
advancement_folder_xmas = "\U0001fa8e讀"
data_folder_closed = "\U0001fa8e拏"
spyglass_file = "\U0001fa8e樂"
docker_file = "\U0001fa8e諾"
arduino_file = "\U0001fa8e丹"
scala_file = "\U0001fa8e寧"
nim_folder_xmas = "\U0001fa8e怒"
attachables_folder = "\U0001fa8e率"
trim_pattern_folder_xmas = "\U0001fa8e異"
waypoint_style_folder_xmas = "\U0001fa8e北"
bukkit_file = "\U0001fa8e磻"
nim_folder = "\U0001fa8e便"
recipe_file = "\U0001fa8e復"
ant_file = "\U0001fa8e不"
archive_file = "\U0001fa8e泌"
blockbench_file = "\U0001fa8e數"
generic_folder_xmas = "\U0001fa8e索"
terraform_folder = "\U0001fa8e參"
css_file = "\U0001fa8e塞"
vlang_file = "\U0001fa8e省"
lang_folder = "\U0001fa8e葉"
structure_folder_xmas = "\U0001fa8e說"
dialog_folder_xmas = "\U0001fa8e殺"
chicken_variant_folder = "\U0001fa8e辰"
dimension_type_folder = "\U0001fa8e沈"
equipment_folder = "\U0001fa8e拾"
damage_type_file = "\U0001fa8e若"
frog_variant_file = "\U0001fa8e掠"
models_folder_xmas = "\U0001fa8e略"
function_folder = "\U0001fa8e亮"
modrinth_file = "\U0001fa8e兩"
predicate_folder = "\U0001fa8e凉"
elixir_file = "\U0001fa8e梁"
linux_file = "\U0001fa8e糧"
sandstone_file = "\U0001fa8e良"
damage_type_folder = "\U0001fa8e諒"
git_file = "\U0001fa8e量"
reason_react_file = "\U0001fa8e勵"
mcbuild_file = "\U0001fa8e呂"
wolf_variant_file = "\U0001fa8e女"
vs_folder = "\U0001fa8e廬"
log_file = "\U0001fa8e旅"
trial_spawner_file = "\U0001fa8e濾"
tags_file = "\U0001fa8e礪"
"sounds.json_file" = "\U0001fa8e閭"
item_modifier_file = "\U0001fa8e驪"
text_file = "\U0001fa8e麗"
typst_folder_xmas = "\U0001fa8e黎"
"blocks.json_file" = "\U0001fa8e力"
spigot_file = "\U0001fa8e曆"
java_file = "\U0001fa8e歷"
julia_file = "\U0001fa8e轢"
todo_file = "\U0001fa8e年"
image_folder = "\U0001fa8e憐"
database_folder_xmas = "\U0001fa8e戀"
shaders_folder_xmas = "\U0001fa8e撚"
text_folder_xmas = "\U0001fa8e漣"
vala_file = "\U0001fa8e煉"
instrument_file = "\U0001fa8e璉"
css_folder = "\U0001fa8e秊"
glsl_file = "\U0001fa8e練"
neovim_folder_xmas = "\U0001fa8e聯"
trim_material_folder = "\U0001fa8e輦"
npm_folder_xmas = "\U0001fa8e蓮"
typst_folder = "\U0001fa8e連"
paper_file = "\U0001fa8e鍊"
waypoint_style_file = "\U0001fa8e列"
groovy_file = "\U0001fa8e劣"
recipe_folder_xmas = "\U0001fa8e咽"
blockstates_folder_xmas = "\U0001fa8e烈"
dimension_type_file = "\U0001fa8e裂"
instrument_folder_xmas = "\U0001fa8e說"
